<?php

use Illuminate\Database\Seeder;
use App\Perfil;

class PerfilTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'prisciliano gerardo';
        $perfil->perfil_apellidos = 'Illescas Lozano';
        $perfil->perfil_tarjeta = '000000000001';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 1;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'adriana';
        $perfil->perfil_apellidos = 'lópez montecinos';
        $perfil->perfil_tarjeta = '000000000002';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 2;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'andrés';
        $perfil->perfil_apellidos = 'martínez guzmán';
        $perfil->perfil_tarjeta = '000000000003';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 3;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'ricardo';
        $perfil->perfil_apellidos = 'fernández hernández';
        $perfil->perfil_tarjeta = '000000000004';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 4;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'fredy';
        $perfil->perfil_apellidos = '';
        $perfil->perfil_tarjeta = '000000000005';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 5;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'william wilver';
        $perfil->perfil_apellidos = 'días contreras';
        $perfil->perfil_tarjeta = '000000000006';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 6;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'laura';
        $perfil->perfil_apellidos = 'moreno paredes';
        $perfil->perfil_tarjeta = '000000000007';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 7;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'maría josé';
        $perfil->perfil_apellidos = 'flores salazar';
        $perfil->perfil_tarjeta = '000000000008';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 8;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();
        
        $perfil = new Perfil();
        $perfil->perfil_nombre = 'laura patricia';
        $perfil->perfil_apellidos = 'zamudio hernández';
        $perfil->perfil_tarjeta = '000000000009';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 9;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'cyntia';
        $perfil->perfil_apellidos = 'bolaños pérez';
        $perfil->perfil_tarjeta = '000000000010';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 10;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();
 
        $perfil = new Perfil();
        $perfil->perfil_nombre = 'yuliana nicol';
        $perfil->perfil_apellidos = '';
        $perfil->perfil_tarjeta = '000000000011';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 11;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        ///usuarios deshabilitados

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'laura';
        $perfil->perfil_apellidos = '';
        $perfil->perfil_tarjeta = '000000000012';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 12;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'janet ';
        $perfil->perfil_apellidos = 'moreno russel';
        $perfil->perfil_tarjeta = '000000000013';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 13;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'andrea';
        $perfil->perfil_apellidos = 'gonzalez alba';
        $perfil->perfil_tarjeta = '000000000014';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 14;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'araceli';
        $perfil->perfil_apellidos = 'díaz najera';
        $perfil->perfil_tarjeta = '000000000015';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 15;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'susen';
        $perfil->perfil_apellidos = 'gutierrez';
        $perfil->perfil_tarjeta = '000000000016';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 16;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'aldo gerardo';
        $perfil->perfil_apellidos = 'reyes morales';
        $perfil->perfil_tarjeta = '000000000017';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 17;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'juan';
        $perfil->perfil_apellidos = 'eloy espindola';
        $perfil->perfil_tarjeta = '000000000018';
        $perfil->perfil_genero = 'M';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 18;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

        $perfil = new Perfil();
        $perfil->perfil_nombre = 'yoali';
        $perfil->perfil_apellidos = 'rivera loo';
        $perfil->perfil_tarjeta = '000000000019';
        $perfil->perfil_genero = 'F';
        $perfil->perfil_nacimiento = '2000-01-01';
        $perfil->perfil_celular = NULL;
        $perfil->perfil_compania = NULL;
        $perfil->avatar_id = 0;
        $perfil->tipo_perfil_id = 1;
        $perfil->clasificacion_id = NULL;
        $perfil->empresa_id = 1;
        $perfil->ciudad_id = 1;
        $perfil->vendedor_id = 1;
        $perfil->user_id = 19;
        $perfil->created_at = NULL;
        $perfil->updated_at = NULL;
        $perfil->save();

    }
}
